apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "{{ .Values.database.postgres.managingTeam }}-{{ include "cloud-agent.name" . }}-postgres-cluster"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  teamId: "{{ .Values.database.postgres.managingTeam }}"
  volume:
    size: "{{ .Values.database.postgres.databaseSize }}"
  numberOfInstances: {{ .Values.database.postgres.numberOfInstances }}
  nodeAffinity:
    {{- toYaml .Values.affinity.nodeAffinity | nindent 4 }}
  tolerations:
    {{- toYaml .Values.tolerations | nindent 4 }}
  resources:
    {{- toYaml .Values.database.postgres.resources | nindent 4 }}
  users:
    pollux-admin:
      - superuser
      - createdb
    pollux-application-user:
      - login
    connect-admin:
      - superuser
      - createdb
    connect-application-user:
      - login
    agent-admin:
      - superuser
      - createdb
    agent-application-user:
      - login
  databases:
    pollux: pollux-admin
    connect: connect-admin
    agent: agent-admin
  postgresql:
    version: "14"

{{- if .Values.keycloak.enabled }}
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "{{ .Values.database.postgres.managingTeam }}-keycloak-postgres-cluster"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  teamId: "{{ .Values.database.postgres.managingTeam }}"
  volume:
    size: "{{ .Values.database.postgres.databaseSize }}"
  numberOfInstances: {{ .Values.database.postgres.numberOfInstances }}
  users:
    keycloak-admin:
      - superuser
      - createdb
    keycloak-user: []
  databases:
    keycloak: keycloak-admin
  postgresql:
    version: "14"
  sidecars:
    - name: postgres-exporter
      image: wrouesnel/postgres_exporter
      ports:
        - containerPort: 9187
          name: metrics
      env:
        - name: DATASOURCE_URI
          value: "postgresql://localhost:5432/ranger?sslmode=disable"
        - name: DATA_SOURCE_USER
          value: "$(POSTGRES_USER)"
        - name: DATA_SOURCE_PASS
          value: "$(POSTGRES_PASSWORD)"
      resources:
        limits:
          cpu: 50m
          memory: 150Mi
        requests:
          cpu: 50m
          memory: 150Mi
{{- end }}















