apiVersion: v1
entries:
  prism-agent:
    - apiVersion: v2
      appVersion: 1.19.0-snapshot.1
      created: "2023-11-16T08:27:09.334790111Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: a1f8f9ea0d21dda6a41177a353ca6047240c7958e9f9710435a33b6593579790
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.19.0-snapshot.1.tgz
      version: 1.19.0-snapshot.1
    - apiVersion: v2
      appVersion: 1.18.0
      created: "2023-11-16T08:27:09.331988025Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 5a803d916bc19c824aec9d39efb0206ff9a2a3b1932b276acaaf97c580f62387
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.18.0.tgz
      version: 1.18.0
    - apiVersion: v2
      appVersion: 1.17.0
      created: "2023-11-16T08:27:09.328294153Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: a53050003aedfd0a7d78014dfe9e819c6e2a1db442eeaac6971cff354cf0d3d4
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.17.0.tgz
      version: 1.17.0
    - apiVersion: v2
      appVersion: 1.16.4
      created: "2023-11-16T08:27:09.325453135Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 05c9159bea902724bb8c8c395bb00d5a3305602e8ace94fe0dd94c1064384fc5
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.4.tgz
      version: 1.16.4
    - apiVersion: v2
      appVersion: 1.16.3
      created: "2023-11-16T08:27:09.322070956Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 309200472891b513a19fad3c3a84745ee95afad6b4680924e81b497f4d8736d3
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.3.tgz
      version: 1.16.3
    - apiVersion: v2
      appVersion: 1.16.2
      created: "2023-11-16T08:27:09.319230178Z"
      dependencies:
        - name: vault
          repository: https://helm.releases.hashicorp.com
          version: 0.24.1
      description: A Helm chart for deploying prism-agent
      digest: 0ffa1f3b0748da032ff40900bc4bb55e4a64c400b31cc8796880da4aa7557529
      name: prism-agent
      type: application
      urls:
        - https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent/main/infrastructure/charts/prism-agent-1.16.2.tgz
      version: 1.16.2
generated: "2023-11-16T08:27:09.316193045Z"
